# Generated by Django 2.0.5 on 2018-08-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
