# Generated by Django 2.0.5 on 2018-08-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxP', '0002_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='registered_datetime',
            field=models.DateTimeField(),
        ),
    ]
